# Função para aguardar a tecla Enter ser pressionada
def aguardar_enter():
    input("\nPressione Enter para continuar...")

print("Receita de Bolo de Chocolate \n")

# Exibição dos ingredientes
print("Ingredientes:")
print("2 xícaras de farinha de trigo")
aguardar_enter()
print("1 xícara de açúcar")
aguardar_enter()
print("1/2 xícara de cacau em pó")
aguardar_enter()
print("1 colher de chá de fermento em pó")
aguardar_enter()
print("1 colher de chá de bicarbonato de sódio")
aguardar_enter()
print("1/2 colher de chá de sal")
aguardar_enter()
print("2 ovos")
aguardar_enter()
print("1 xícara de leite")
aguardar_enter()
print("1/2 xícara de óleo vegetal")
aguardar_enter()
print("2 colheres de chá de extrato de baunilha")
aguardar_enter()
print("1 xícara de água fervente")
aguardar_enter()

# Exibição do modo de preparo
print("\nModo de preparo:")
print("Pré-aqueça o forno a 180°C. Unte uma forma de bolo com manteiga e farinha, ou forre-a com papel manteiga.")
aguardar_enter()
print("Em uma tigela grande, peneire a farinha de trigo, o açúcar, o cacau em pó, o fermento em pó, o bicarbonato de sódio e o sal. Misture bem.")
aguardar_enter()
print("Em outra tigela, bata os ovos levemente. Adicione o leite, o óleo vegetal e o extrato de baunilha. Misture bem.")
aguardar_enter()
print("Despeje os ingredientes líquidos na mistura de ingredientes secos e mexa até que tudo esteja bem combinado.")
aguardar_enter()
print("Adicione a água fervente à massa e misture até que a massa fique homogênea. A massa ficará líquida, mas é normal.")
aguardar_enter()
print("Despeje a massa na forma preparada e leve ao forno pré-aquecido.")
aguardar_enter()
print("Asse por cerca de 30-35 minutos, ou até que um palito inserido no centro do bolo saia limpo.")
aguardar_enter()
print("Retire o bolo do forno e deixe esfriar na forma por alguns minutos. Em seguida, transfira para uma grade de resfriamento para esfriar completamente.")
aguardar_enter()
print("Depois de esfriar, você pode servir o bolo simples ou decorá-lo com cobertura de sua preferência, como ganache de chocolate ou glacê de chocolate.")